# Install HAProxy and keepalived

- name: Add keepalived repository
  apt_repository: repo='deb http://ppa.launchpad.net/keepalived/stable/ubuntu trusty main' filename=keepalived
  become: true

- name: Install keepalived
  apt: name=keepalived update_cache=yes
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5
  
- name: Install haproxy
  apt: name=haproxy update_cache=yes
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5
  
- name: Modify /etc/sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv4.ip_nonlocal_bind=1"
  become: true
  
- name: Reset sysctl
  command: /sbin/sysctl -p
  
- name: Create keepalived configuration
  template: src=roles/haproxy/templates/etc/keepalived/keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf backup=no force=yes
  become: true
  
- name: Create HAproxy configuration
  template: src=roles/haproxy/templates/etc/haproxy/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg backup=no force=yes
  become: true
  
- name: Modify /etc/default/haproxy
  lineinfile: dest=/etc/default/haproxy line="ENABLED=1"
  become: true
  
- name: Modify /etc/default/haproxy
  lineinfile: dest=/etc/default/haproxy line="ENABLED=0" state=absent
  become: true
  
- name: Run keepalived 
  service: name=keepalived state=restarted
  become: true
  
- name: Run haproxy
  service: name=haproxy state=restarted
  become: true