# Install cloudone_node_health

- name: Creates directory /srv/cloudone_node_health
  file: path=/srv/cloudone_node_health state=directory
  become: true

# Create only if not existing
- name: Create /srv/cloudone_node_health/cloudone_node_health.py
  template: src=roles/shared/templates/srv/cloudone_node_health/cloudone_node_health.py_node.j2 dest=/srv/cloudone_node_health/cloudone_node_health.py backup=no force=no
  become: true

# Copy only if not existing
- name: Copy /etc/init/cloudone_node_health.conf
  copy: src=roles/shared/files/etc/init/cloudone_node_health.conf dest=/etc/init/cloudone_node_health.conf force=no
  become: true

# Incrementally add role
- name: Incrementally add role to /srv/cloudone_node_health/cloudone_node_health.py
  lineinfile: dest=/srv/cloudone_node_health/cloudone_node_health.py insertafter="class CloudOneNodeHealth:" line="\t{{ host_type_line }}"
  become: true
  
- name: Run cloudone_node_health
  service: name=cloudone_node_health state=restarted
  become: true
