# Install flannel
  
- name: Copy /opt/bin/flanneld
  copy: src=roles/shared/files/opt/bin/flanneld dest=/opt/bin/flanneld mode=0755
  become: true
  
- name: Copy /etc/init.d/flanneld
  copy: src=roles/shared/files/etc/init.d/flanneld dest=/etc/init.d/flanneld
  become: true

- name: Create /etc/init/flanneld.conf
  template: src=roles/shared/templates/etc/init/flanneld.conf.j2 dest=/etc/init/flanneld.conf backup=no force=yes
  become: true

- name: Create /etc/default/flanneld
  template: src=roles/shared/templates/etc/default/flanneld.j2 dest=/etc/default/flanneld backup=no force=yes
  become: true

- name: Run flanneld
  service: name=flanneld state=started
  become: true
  
