# Uninstall kubeconfig

- name: Delete /srv/kubeconfig/kubeconfig.yaml
  file: path=/srv/kubeconfig/kubeconfig.yaml state=absent
  become: true

- name: Delete directory /srv/kubeconfig recursively
  file: path=/srv/kubeconfig state=absent
  become: true