# Install kubeconfig

- name: Creates directory /srv/kubeconfig
  file: path=/srv/kubeconfig state=directory
  become: true

- name: Create /srv/kubeconfig/kubeconfig.yaml
  template: src=roles/shared/templates/srv/kubeconfig/kubeconfig.yaml.j2 dest=/srv/kubeconfig/kubeconfig.yaml backup=no force=yes
  become: true