# Module requirement

- name: Install docker-py
  pip: name=docker-py version=1.9.0
  become: yes

# Retrieve

- name: Retrieve cloudawan/cloudone
  docker_image:
    name: cloudawan/cloudone
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Retrieve cloudawan/cloudone_gui
  docker_image:
    name: cloudawan/cloudone_gui
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Retrieve cloudawan/cloudone_analysis
  docker_image:
    name: cloudawan/cloudone_analysis
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Retrieve cloudawan/elasticsearch
  docker_image:
    name: cloudawan/elasticsearch
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Retrieve cloudawan/spark_master
  docker_image:
    name: cloudawan/spark_master
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Retrieve cloudawan/spark_worker
  docker_image:
    name: cloudawan/spark_worker
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5