# Module requirement

- name: Install docker-py
  pip: name=docker-py version=1.9.0
  become: yes

# Retrieve

- name: Retrieve cloudawan/cassandra
  docker_image:
    name: cloudawan/cassandra
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Retrieve cloudawan/mariadb-galera
  docker_image:
    name: cloudawan/mariadb-galera
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5
  
- name: Retrieve cloudawan/rabbitmq
  docker_image:
    name: cloudawan/rabbitmq
  become: yes
  register: result
  until: result|success
  retries: 3
  delay: 5