# Create temporarily templates

- name: Create cloudone host credential script
  template: src=roles/node/templates/cloudone_host_credential_configure.py.j2 dest=/tmp/cloudone_host_credential_configure.py backup=no force=yes

# Run templates

- name: Run cloudone host credential script
  command: /usr/bin/python /tmp/cloudone_host_credential_configure.py

# Delete temporarily templates

- name: Delete cloudone_host_credential_configure.py
  file: path=/tmp/cloudone_host_credential_configure.py state=absent