# Create temporarily templates

- name: Create cloudone host credential delete script
  template: src=roles/node/templates/cloudone_host_credential_delete.py.j2 dest=/tmp/cloudone_host_credential_delete.py backup=no force=yes

# Run templates

- name: Run cloudone host credential delete script
  command: /usr/bin/python /tmp/cloudone_host_credential_delete.py
  ignore_errors: yes

# Delete temporarily templates

- name: Delete cloudone_host_credential_delete.py
  file: path=/tmp/cloudone_host_credential_delete.py state=absent