# Linux bridge
# Used to configure docker's default network
  
- name: Install linux bridge
  apt: name=bridge-utils update_cache=yes
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5

# Docker
  
- name: Add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' filename=docker
  become: true
  
- name: Add apt-get key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5

- name: Run apt-get update and install docker
  apt: name=docker-engine=1.10.3-0~trusty update_cache=yes
  become: true
  register: result
  until: result|success
  retries: 3
  delay: 5

# Copy docker configuration

- name: Copy /etc/default/docker
  copy: src=roles/node/files/etc/default/docker dest=/etc/default/docker
  become: true
  
- name: Copy /etc/init/docker.conf
  copy: src=roles/node/files/etc/init/docker.conf dest=/etc/init/docker.conf
  become: true
  
- name: Restart docker
  service: name=docker state=restarted
  become: true