# Create temporarily templates

- name: Create kubernetes notify apiserver to delete node script
  template: src=roles/node/templates/kubernetes_notify_apiserver_to_delete_node.py.j2 dest=/tmp/kubernetes_notify_apiserver_to_delete_node.py backup=no force=yes

# Run templates

- name: Run kubernetes notify apiserver to delete node script
  command: /usr/bin/python /tmp/kubernetes_notify_apiserver_to_delete_node.py
  ignore_errors: yes

# Delete temporarily templates

- name: Delete kubernetes_notify_apiserver_to_delete_node.py
  file: path=/tmp/kubernetes_notify_apiserver_to_delete_node.py state=absent