# Prepare certificates

- name: Creates directory
  file: path=/etc/docker state=directory
  become: true
  
- name: Creates directory
  file: path=/etc/docker/certs.d state=directory
  become: true
  
- name: Creates directory
  file: path=/etc/docker/certs.d/private-registry:31000 state=directory
  become: true
  
- name: Copy /srv/kubernetes/cacert.pem
  copy: src=roles/node/files/srv/kubernetes/cacert.pem dest=/etc/docker/certs.d/private-registry:31000/ca.crt
  become: true

- name: Copy /srv/kubernetes/private_registry_cert.pem
  copy: src=roles/node/files/srv/kubernetes/private_registry_cert.pem dest=/srv/kubernetes/private_registry_cert.pem
  become: true
  
- name: Copy /srv/kubernetes/private_registry_key.pem
  copy: src=roles/node/files/srv/kubernetes/private_registry_key.pem dest=/srv/kubernetes/private_registry_key.pem
  become: true
