# create

- name: Copy etcd-service.json
  copy: src=roles/master_node/files/etcd-service.json dest=/tmp/etcd-service.json

- name: Copy cloudone-controller-glusterfs.json
  copy: src=roles/master_node/files/cloudone-controller-glusterfs.json dest=/tmp/cloudone-controller-glusterfs.json

- name: Copy cloudone-service.json
  copy: src=roles/master_node/files/cloudone-service.json dest=/tmp/cloudone-service.json

- name: Create etcd-endpoints.yaml
  template: src=roles/master_node/templates/etcd-endpoints.yaml.j2 dest=/tmp/etcd-endpoints.yaml backup=no force=yes

- name: Create etcd-service.json
  command: /usr/local/bin/kubectl create -f /tmp/etcd-service.json
  
- name: Create etcd-endpoints.yaml
  command: /usr/local/bin/kubectl create -f /tmp/etcd-endpoints.yaml

- name: Create cloudone-controller-glusterfs.json
  command: /usr/local/bin/kubectl create -f /tmp/cloudone-controller-glusterfs.json

- name: Create cloudone-service.json
  command: /usr/local/bin/kubectl create -f /tmp/cloudone-service.json