- name: Create cloudone host credential script
  template: src=roles/master_node/templates/cloudone_host_credential_configure.py.j2 dest=/tmp/cloudone_host_credential_configure.py backup=no force=yes

- name: Run cloudone host credential script
  command: /usr/bin/python /tmp/cloudone_host_credential_configure.py
