# private registry

- name: Create volume
  command: /usr/sbin/gluster volume create private_registry_volume replica 2 {{ software_replica_host_1 }}:/data/glusterfs/private_registry_volume {{ software_replica_host_2 }}:/data/glusterfs/private_registry_volume force
  become: true
  
- name: Start volume
  command: /usr/sbin/gluster volume start private_registry_volume
  become: true
  
# cloudone

- name: Create volume
  command: /usr/sbin/gluster volume create cloudone_elasticsearch_volume replica 2 {{ software_replica_host_1 }}:/data/glusterfs/cloudone_elasticsearch_volume {{ software_replica_host_2 }}:/data/glusterfs/cloudone_elasticsearch_volume force
  become: true
  
- name: Start volume
  command: /usr/sbin/gluster volume start cloudone_elasticsearch_volume
  become: true
  
- name: Configure volume
  command: /usr/sbin/gluster volume set cloudone_elasticsearch_volume performance.md-cache-timeout 0
  become: true

- name: Configure volume
  command: /usr/sbin/gluster volume set cloudone_elasticsearch_volume performance.write-behind off
  become: true
  
- name: Configure volume
  command: /usr/sbin/gluster volume set cloudone_elasticsearch_volume performance.read-ahead off
  become: true
  
- name: Configure volume
  command: /usr/sbin/gluster volume set cloudone_elasticsearch_volume performance.io-cache off
  become: true
  
- name: Configure volume
  command: /usr/sbin/gluster volume set cloudone_elasticsearch_volume performance.quick-read off
  become: true

- name: Configure volume
  command: /usr/sbin/gluster volume set cloudone_elasticsearch_volume performance.stat-prefetch off
  become: true

- name: Configure volume
  command: /usr/sbin/gluster volume set cloudone_elasticsearch_volume performance.readdir-ahead off
  become: true

- name: Create volume
  command: /usr/sbin/gluster volume create cloudone_gui_configuration_volume replica 2 {{ software_replica_host_1 }}:/data/glusterfs/cloudone_gui_configuration_volume {{ software_replica_host_2 }}:/data/glusterfs/cloudone_gui_configuration_volume force
  become: true

- name: Start volume
  command: /usr/sbin/gluster volume start cloudone_gui_configuration_volume
  become: true
  