# Shared

- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/common_install.yml

- hosts: glusterfs_host
  tasks:
  - include: roles/shared/tasks/common_install.yml

- hosts: haproxy_host
  tasks:
  - include: roles/shared/tasks/common_install.yml

- hosts: master_node_host
  vars:
    certificate_ca_required: False
    master_host_ip: "{{ hostvars[groups['haproxy'][0]]['haproxy_floating_ip'] }}"
  tasks:
  - include: roles/shared/tasks/kubernetes_certificate_generate.yml
    run_once: true
  
- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/kubernetes_certificate_copy.yml

- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/kubeconfig_install.yml

# Master

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/etcd_install.yml

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/flannel_preconfigure.yml
    run_once: true

- hosts: master_node_host
  vars:
    line_start_on: "start on started etcd"
    line_stop_on: "stop on stopping etcd"
    master_host_ip: "{{ inventory_hostname }}"
  tasks:
  - include: roles/shared/tasks/flannel_install.yml

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/kubernetes_master_install.yml

# Node

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/hosts_install.yml

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/docker_install.yml

- hosts: master_node_host
  vars:
    master_host_ip: "{{ inventory_hostname }}"
  tasks:
  - include: roles/node/tasks/kubernetes_node_install.yml

# Glusterfs server

- hosts: glusterfs_host
  tasks:
  - include: roles/glusterfs/tasks/glusterfs_install.yml

- hosts: glusterfs_host
  tasks:
  - include: roles/glusterfs/tasks/glusterfs_join.yml
  
- hosts: glusterfs_host
  tasks:
  - include: roles/glusterfs/tasks/glusterfs_create_volume.yml
    run_once: true

# Service/Application on the Kubernetes

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/kube_dns.yml
    run_once: true

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/glusterfs_default_endpoint.yml
    run_once: true

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/private_registry_certificate.yml

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/private_registry_create.yml
    run_once: true

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/cloudone_image_retrieve.yml

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/cloudone_create.yml
    run_once: true

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/cloudawan_image_retrieve.yml

# Configure on cloudone

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/cloudone_glusterfs_cluster_configure.yml
    run_once: true

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/cloudone_private_registry_configure.yml
    run_once: true

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/cloudone_host_credential_configure.yml
    run_once: true

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/cloudone_third_party_service_template_import.yml
    run_once: true

# HAproxy

- hosts: haproxy_host
  tasks:
  - include: roles/haproxy/tasks/haproxy_install.yml

- hosts: haproxy_host
  tasks:
  - include: roles/haproxy/tasks/cloudone_slb_install.yml

- hosts: master_node_host
  tasks:
  - include: roles/master/tasks/cloudone_slb_daemon_configure.yml
    run_once: true

# Cloudone node health
# The role is incrementally added

- hosts: master_node_host
  vars:
    host_type_line: HostTypeKubernetes=True
    master_host_ip: 127.0.0.1
  tasks:
  - include: roles/shared/tasks/cloudone_node_health_install.yml

- hosts: glusterfs_host
  vars:
    host_type_line: HostTypeGlusterfs=True
    master_host_ip: "{{ master_host_slb_vip }}"
  tasks:
  - include: roles/shared/tasks/cloudone_node_health_install.yml

- hosts: haproxy_host
  vars:
    host_type_line: HostTypeSLB=True
    master_host_ip: "{{ haproxy_floating_ip }}"
  tasks:
  - include: roles/shared/tasks/cloudone_node_health_install.yml
