# Shared

- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/common_install.yml

- hosts: master_node_host
  vars:
    certificate_ca_required: True
    master_host_ip: "{{ master_host_slb_vip }}"
  tasks:
  - include: roles/shared/tasks/kubernetes_certificate_generate.yml
    run_once: true
  
- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/kubernetes_certificate_copy.yml

- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/kubeconfig_install.yml

# Node

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/hosts_install.yml

- hosts: master_node_host
  vars:
    line_start_on: "start on net-device-up IFACE!=lo"
    line_stop_on: "stop on runlevel [!2345]"
    master_host_ip: "{{ master_host_slb_vip }}"
  tasks:
  - include: roles/shared/tasks/flannel_install.yml

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/docker_install.yml

- hosts: master_node_host
  vars:
    master_host_ip: "{{ master_host_slb_vip }}"
  tasks:
  - include: roles/node/tasks/kubernetes_node_install.yml

# Configure on cloudone

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/cloudone_host_credential_configure.yml

# Service/Application on the Kubernetes

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/private_registry_certificate.yml

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/cloudawan_image_retrieve.yml

# Cloudone node health
# The role is incrementally added

- hosts: master_node_host
  vars:
    host_type_line: HostTypeKubernetes=True
    master_host_ip: "{{ master_host_slb_vip }}"
  tasks:
  - include: roles/shared/tasks/cloudone_node_health_install.yml