# Shared

- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/common_install.yml

# Node

- hosts: master_node_host
  tasks:
  - include: roles/shared/tasks/flannel_external_etcd_install.yml

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/docker_install.yml

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/docker_reconfigure.yml

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/kubernetes_node_external_master_install.yml

# Configure hostname of private-registry

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/hosts.yml

# Configure on cloudone

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/cloudone_host_credential_configure.yml

# Service/Application on the Kubernetes

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/private_registry_certificate.yml

- hosts: master_node_host
  tasks:
  - include: roles/node/tasks/cloudawan_image_retrieve.yml

# Cloudone node health
# The role is incrementally added

- hosts: master_node_host
  vars:
    host_type_line: HostTypeKubernetes=True
    master_host_ip: {{ master_host_slb_vip }}
  tasks:
  - include: roles/shared/tasks/cloudone_node_health_install.yml