# Create temporarily templates

- name: Create cloudone private registry script
  template: src=roles/master/templates/cloudone_private_registry_configure.py.j2 dest=/tmp/cloudone_private_registry_configure.py backup=no force=yes

# Run templates

- name: Run cloudone private registry script
  command: /usr/bin/python /tmp/cloudone_private_registry_configure.py

# Delete temporarily templates

- name: Delete cloudone_private_registry_configure.py
  file: path=/tmp/cloudone_private_registry_configure.py state=absent