# Create temporarily templates

- name: Create cloudone glusterfs cluster script
  template: src=roles/master/templates/cloudone_glusterfs_cluster_create.py.j2 dest=/tmp/cloudone_glusterfs_cluster_create.py backup=no force=yes

# Run templates

- name: Run cloudone glusterfs cluster script
  command: /usr/bin/python /tmp/cloudone_glusterfs_cluster_create.py

# Delete temporarily templates

- name: Delete cloudone_glusterfs_cluster_create.py
  file: path=/tmp/cloudone_glusterfs_cluster_create.py state=absent