# Install etcd
  
- name: Copy /opt/bin/etcd
  copy: src=roles/master/files/opt/bin/etcd dest=/opt/bin/etcd mode=0755
  become: true
  
- name: Copy /opt/bin/etcdctl
  copy: src=roles/master/files/opt/bin/etcdctl dest=/opt/bin/etcdctl mode=0755
  become: true
  
- name: Copy /etc/init.d/etcd
  copy: src=roles/master/files/etc/init.d/etcd dest=/etc/init.d/etcd mode=0755
  become: true

- name: Copy /etc/init/etcd.conf
  copy: src=roles/master/files/etc/init/etcd.conf dest=/etc/init/etcd.conf mode=0755
  become: true

- name: Create the /etc/default/etcd file for all machines
  template: src=roles/master/templates/etc/default/etcd.j2 dest=/etc/default/etcd backup=no force=yes
  become: true

- name: Run etcd
  service: name=etcd state=started
  become: true