# Delete directory /infra{{ inventory_hostname }}.etcd recursively

- name: Delete directory /infra{{ inventory_hostname }}.etcd recursively
  file: path=/infra{{ inventory_hostname }}.etcd state=absent
  become: true